name: Deploy to EC2 on merge

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Install SSH key
              uses: webfactory/ssh-agent@v0.6.0
              with:
                ssh-private-key: ${{ secrets.SERVER_SSH_PRIVATE_KEY }}

            - name: Cache spaCy model
              id: cache-spacy
              uses: actions/cache@v2
              with:
                path: ~/.cache/spacy
                key: ${{ runner.os }}-spacy-en_core_web_md
                restore-keys: |
                  ${{ runner.os }}-spacy

            - name: Update code
              run: |
                ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.SERVER_IP_ADDRESS }} << 'EOF'
                  echo "Hello from github action, start deploy main to ec2"
                  cd ~/porko/personal-project
                  git switch action
                  git pull
                  cd server

                  # Activate Python venv and install modules
                  source ./myvenv/bin/activate
                  python3 -m pip install --upgrade pip
                  pip install -r requirements.txt

                  # Download model if not cached
                  python3 download_model.py

                  # Node dependencies
                  npm install
                  npm install pm2 -g

                  # Start server
                  pm2 stop all || true
                  pm2 start app.js --name "porko"
                  pm2 save
                EOF
